ajaxcrud/crud/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crudajaxapp.urls', namespace='crud')),
]

ajaxcrud/crud/crudajaxapp/urls.py
from django.urls import path
from . import views

app_name = 'crud'
urlpatterns = [
    path('', views.home, name='home'),
    path('save/', views.save_data, name='save'),
]

ajaxcrud/crud/crudajaxapp/models.py
from django.db import models


# Create your models here.

class User(models.Model):
    name = models.CharField(max_length=70)
    email = models.EmailField(max_length=100)
    password = models.CharField(max_length=100)

ajaxcrud/crud/crudajaxapp/forms.py
from django import forms
from .models import User


class UserRegForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['name', 'email', 'password']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'id': 'nameid'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'id': 'emailid'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'id': 'passwordid'}),
        }

ajaxcrud/crud/crudajaxapp/views.py
from django.shortcuts import render
from .forms import UserRegForm
from .models import User
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt


# Create your views here.

def home(request):
    form = UserRegForm()
    data = User.objects.all()
    return render(request, 'C:/Users/PC/Desktop/python proj/ajaxcrud/crud/crudajaxapp/templates/home.html',
                  {'form': form, 'data': data})

@csrf_exempt
def save_data(request):
    if request.method == "POST":
        form = UserRegForm(request.POST)
        print("SAVE VEIW FUNC")
        if form.is_valid():
            name = request.POST['name']
            email = request.POST['email']
            password = request.POST['password']
            usr = User(name=name, email=email, password=password)
            usr.save()
            return JsonResponse({'status': 'save'})
    else:
        return JsonResponse({'status': 0})

ajaxcrud/crud/crudajaxapp/templates/ajax.html
  <script>

    $("#btnsave").click(function() {

        let nm = $("#nameid").val();
        let em = $("#emailid").val();
        let pw = $("#passwordid").val();

        console.log(nm);
        if (nm == ""){
          console.log("please enter name");
        } else if (em == ""){
          console.log("please enter email");
        } else if (pw == ""){
          console.log("please enter password");
        }else{
          console.log("AJAx RUNNING");
          mydata = { name: nm, email: em, password: pw};
                              console.log(mydata);
          $.ajax({
          url: "/save/",
          method: "POST",
          data: mydata,
          success:function(data){
          console.log(data)
          },
          });
        }
    });

</script>

ajaxcrud/crud/crudajaxapp/templates/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <title>AJAX CRUD</title>
  </head>
  <body>
    <h1 class="text-center alert alert-danger">User Data</h1>
    <div class="row">
      <div class=" col-sm-4 text-center">
        <h4 class="text-center alert alert_info">Add/update</h4>
        <form action="" method="POST">
          {% csrf_token %}
          {% for fm in form %}
          {{fm.label_tag}} {{fm}} {{fm.errors|striptags}}
          <br>
          <br>
          {% endfor %}
          <input type="submit" id="btnsave" class="btn btn-success" value="ADD/UPDATE">
        </form>
      </div>
      <div class=" col-sm-7 text-center">
        <h4 class="text-center alert alert_info">Show Student Information</h4>
        <table class="text-center">
          <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">NAME</th>
            <th scope="col">EMAIL</th>
            <th scope="col">PASSWORD</th>
            <th scope="col">ACTION</th>
          </tr>
          </thead>
          <tbody>
              {% for dt in data %}
              <tr>
                <td>{{dt.id}}</td>
                <td>{{dt.name}}</td>
                <td>{{dt.email}}</td>
                <td>{{dt.password}}</td>
                <td><a href="/edit/{{ dt.id }}"><button class="btn btn-secondary" >Edit</button></a></td>
                <td><a href="/edit/{{ dt.id }}"><button class="btn btn-primary" >Delete</button></a></td>
              </tr>
              {% endfor %}
          </tbody>
        </table>
      </div>
    </div>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
<!--    {% include "C:/Users/PC/Desktop/python proj/ajaxcrud/crud/crudajaxapp/templates/ajax.html" %}-->
  <script>

    $("#btnsave").click(function() {

        let nm = $("#nameid").val();
        let em = $("#emailid").val();
        let pw = $("#passwordid").val();

        if (nm == ""){
          console.log("please enter name");
        } else if (em == ""){
          console.log("please enter email");
        } else if (pw == ""){
          console.log("please enter password");
        }else{
          console.log("AJAx RUNNING");
          mydata = { name: nm, email: em, password: pw};
                              console.log(mydata);
          $.ajax({
          url: "{% url 'crud:save' %}",
          method: "POST",
          data: mydata,
          success:function(data){
          console.log(data)
          },
          });
        }
    });

</script>

  </body>
</html>